In [38]:
import opendatasets as od
od.download("https://www.kaggle.com/datasets/shrutimehta/nasa-asteroids-classification?datasetId=14512&sortBy=voteCount")

Please provide your Kaggle credentials to download this dataset. Learn more: http://bit.ly/kaggle-creds
Your Kaggle username:Your Kaggle Key:Downloading nasa-asteroids-classification.zip to ./nasa-asteroids-classification

100%|██████████| 3.27M/3.27M [00:00<00:00, 12.3MB/s]

In [39]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [40]:
nasadf = pd.read_csv("/Users/sungwonLee/Documents/STA160/Midterm1/datasets/nasa.csv")
nasadf

,Neo Reference ID,Name,Absolute Magnitude,Est Dia in KM(min),Est Dia in KM(max),Est Dia in M(min),Est Dia in M(max),Est Dia in Miles(min),Est Dia in Miles(max),Est Dia in Feet(min),...,Asc Node Longitude,Orbital Period,Perihelion Distance,Perihelion Arg,Aphelion Dist,Perihelion Time,Mean Anomaly,Mean Motion,Equinox,Hazardous
0,3703080,3703080,21.600,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,417.388066,...,314.373913,609.599786,0.808259,57.257470,2.005764,2.458162e+06,264.837533,0.590551,J2000,True
1,3723955,3723955,21.300,0.146068,0.326618,146.067964,326.617897,0.090762,0.202951,479.225620,...,136.717242,425.869294,0.718200,313.091975,1.497352,2.457795e+06,173.741112,0.845330,J2000,False
2,2446862,2446862,20.300,0.231502,0.517654,231.502122,517.654482,0.143849,0.321655,759.521423,...,259.475979,643.580228,0.950791,248.415038,1.966857,2.458120e+06,292.893654,0.559371,J2000,True
3,3092506,3092506,27.400,0.008801,0.019681,8.801465,19.680675,0.005469,0.012229,28.876199,...,57.173266,514.082140,0.983902,18.707701,1.527904,2.457902e+06,68.741007,0.700277,J2000,False
4,3514799,3514799,21.600,0.127220,0.284472,127.219879,284.472297,0.079051,0.176763,417.388066,...,84.629307,495.597821,0.967687,158.263596,1.483543,2.457814e+06,135.142133,0.726395,J2000,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4682,3759007,3759007,23.900,0.044112,0.098637,44.111820,98.637028,0.027410,0.061290,144.723824,...,164.183305,457.179984,0.741558,276.395697,1.581299,2.457708e+06,304.306025,0.787436,J2000,False
4683,3759295,3759295,28.200,0.006089,0.013616,6.089126,13.615700,0.003784,0.008460,19.977449,...,345.225230,407.185767,0.996434,42.111064,1.153835,2.458088e+06,282.978786,0.884117,J2000,False
4684,3759714,3759714,22.700,0.076658,0.171412,76.657557,171.411509,0.047633,0.106510,251.501180,...,37.026468,690.054279,0.965760,274.692712,2.090708,2.458300e+06,203.501147,0.521698,J2000,False
4685,3759720,3759720,21.800,0.116026,0.259442,116.025908,259.441818,0.072095,0.161210,380.662441,...,163.802910,662.048343,1.185467,180.346090,1.787733,2.458288e+06,203.524965,0.543767,J2000,False
4686,3772978,3772978,19.109,0.400641,0.895860,400.640618,895.859655,0.248946,0.556661,1314.437764,...,187.642183,653.679098,0.876110,222.436688,2.071980,2.458319e+06,184.820424,0.550729,J2000,False

In [41]:
nasadf.columns
# nasadf.columns["Miss Dist.(Astronomical)"]
nasadf.iloc[:, 16:21]

,Miss Dist.(Astronomical),Miss Dist.(lunar),Miss Dist.(kilometers),Miss Dist.(miles),Orbiting Body
0,0.419483,163.178711,6.275369e+07,3.899334e+07,Earth
1,0.383014,148.992630,5.729815e+07,3.560342e+07,Earth
2,0.050956,19.821890,7.622912e+06,4.736658e+06,Earth
3,0.285322,110.990387,4.268362e+07,2.652237e+07,Earth
4,0.407832,158.646713,6.101082e+07,3.791037e+07,Earth
...,...,...,...,...,...
4682,0.041361,16.089413,6.187511e+06,3.844741e+06,Earth
4683,0.006469,2.516399,9.677324e+05,6.013211e+05,Earth
4684,0.061009,23.732393,9.126775e+06,5.671115e+06,Earth
4685,0.260760,101.435493,3.900908e+07,2.423912e+07,Earth
4686,0.462372,179.862671,6.916986e+07,4.298016e+07,Earth

In [42]:
X = nasadf.iloc[:,2:-2]
y = nasadf["Hazardous"]

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 77)

In [46]:
from pycaret.classification import *

In [47]:
clf = setup(data = nasadf, target="Hazardous", session_id=123)

In [49]:
best = compare_models()

In [54]:
models()[models()['Turbo'] == True]

,Name,Reference,Turbo
ID,,,
lr,Logistic Regression,sklearn.linear_model._logistic.LogisticRegression,True
knn,K Neighbors Classifier,sklearn.neighbors._classification.KNeighborsCl...,True
nb,Naive Bayes,sklearn.naive_bayes.GaussianNB,True
dt,Decision Tree Classifier,sklearn.tree._classes.DecisionTreeClassifier,True
svm,SVM - Linear Kernel,sklearn.linear_model._stochastic_gradient.SGDC...,True
ridge,Ridge Classifier,sklearn.linear_model._ridge.RidgeClassifier,True
rf,Random Forest Classifier,sklearn.ensemble._forest.RandomForestClassifier,True
qda,Quadratic Discriminant Analysis,sklearn.discriminant_analysis.QuadraticDiscrim...,True
ada,Ada Boost Classifier,sklearn.ensemble._weight_boosting.AdaBoostClas...,True
gbc,Gradient Boosting Classifier,sklearn.ensemble._gb.GradientBoostingClassifier,True
lda,Linear Discriminant Analysis,sklearn.discriminant_analysis.LinearDiscrimina...,True
et,Extra Trees Classifier,sklearn.ensemble._forest.ExtraTreesClassifier,True
xgboost,Extreme Gradient Boosting,xgboost.sklearn.XGBClassifier,True
lightgbm,Light Gradient Boosting Machine,lightgbm.sklearn.LGBMClassifier,True
dummy,Dummy Classifier,sklearn.dummy.DummyClassifier,True